kind: source
spec:
  name: "cq-source-newrelic"
  registry: "grpc"
  path: "localhost:7777"
  version: "v1.0.0"
  tables: ['*']
  destinations: ["sqlite"]
  spec:
    accounts:
      - name: 'bewiz'
        api_key: 'NRAK-SMYODD87CECC7JNKN8JVKZRM32P'
